"""Sam v2 memory foundation package."""

from .manager import empty_memory, load_memory, save_memory, update_memory
from .session import is_session_recent, load_last_session, save_session_state
from .long_term import (
    MemoryCandidate,
    build_compact_context,
    classify_intent,
    classify_memory_content,
    consolidate_memories,
    create_operational_task,
    create_coding_review,
    ensure_schema as ensure_long_term_schema,
    extract_candidate_memories,
    generate_session_recap,
    get_operational_task,
    get_project_state,
    learn,
    latest_coding_review,
    latest_conversation_summary,
    list_project_states,
    log_turn,
    memory_debug_report,
    recall,
    recall_lessons,
    recall_recent_conversation,
    recent_consolidation_log,
    recent_memory_review_log,
    save_memory_candidate,
    search_memories,
    snapshot,
    store_fact,
    summarize_conversation_if_needed,
    upsert_project_state,
    update_operational_task,
)

__all__ = [
    "MemoryCandidate",
    "empty_memory",
    "load_memory",
    "save_memory",
    "update_memory",
    "save_session_state",
    "load_last_session",
    "is_session_recent",
    "ensure_long_term_schema",
    "build_compact_context",
    "classify_intent",
    "classify_memory_content",
    "consolidate_memories",
    "create_operational_task",
    "create_coding_review",
    "extract_candidate_memories",
    "generate_session_recap",
    "get_operational_task",
    "get_project_state",
    "latest_coding_review",
    "latest_conversation_summary",
    "list_project_states",
    "learn",
    "log_turn",
    "memory_debug_report",
    "recall",
    "recall_lessons",
    "recall_recent_conversation",
    "recent_consolidation_log",
    "recent_memory_review_log",
    "save_memory_candidate",
    "search_memories",
    "snapshot",
    "store_fact",
    "summarize_conversation_if_needed",
    "upsert_project_state",
    "update_operational_task",
]
